### ISSUE TITLE
"six" requirement not listed

### ISSUE THREAD

**Issue by jmickle66666666** [joshuaskelly/tmx2map#1]

**Comment by joshuaskelly** [comment]
It shouldn’t require six (unless that is a child dependency).

**Comment by jmickle66666666** [comment]
I think it is, it asked for it when I ran it (after installing the listed dependencies in requirements.txt)

**Comment by joshuaskelly** [comment]
I setup a new pyenv environment and this repros. It appears that six is a dependency of tmx, but tmx doesn't install it. 🙁
